# Generated by Django 2.1.10 on 2019-07-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsCommerxcatalogFolders',
            fields=[
                ('foldername', models.CharField(blank=True, db_column='FolderName', max_length=255, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('indentlevel', models.SmallIntegerField(blank=True, db_column='IndentLevel', null=True)),
                ('parentid', models.IntegerField(blank=True, db_column='ParentID', null=True)),
            ],
            options={
                'db_table': 'Products_CommerxCatalog_Folders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsCommerxcatalogProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_column='Category', max_length=100)),
                ('QtyService', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('folderlist', models.TextField(blank=True, db_column='FolderList', null=True)),
                ('list', models.FloatField(blank=True, db_column='List', null=True)),
                ('vendorpartnumber', models.CharField(blank=True, db_column='VendorPartNumber', max_length=40, null=True)),
                ('itemtype', models.CharField(db_column='ItemType', max_length=100)),
            ],
            options={
                'db_table': 'Products_CommerxCatalog_Products',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SavedQuotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Company', models.CharField(max_length=25)),
                ('Contact', models.CharField(max_length=25)),
                ('Services', models.ManyToManyField(to='Quotes.ProductsCommerxcatalogProducts')),
            ],
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
