# Generated by Django 2.1 on 2019-07-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='serviceType',
        ),
        migrations.AddField(
            model_name='service',
            name='Price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='Qty',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='ServiceType',
            field=models.CharField(default='service', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='Quality',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='SKU',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='Type',
            field=models.CharField(max_length=100),
        ),
    ]
