# Generated by Django 2.1 on 2019-07-12 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0002_auto_20190708_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Company', models.CharField(max_length=25)),
                ('Services', models.ManyToManyField(to='Quotes.Service')),
            ],
        ),
    ]
