# Generated by Django 2.1.10 on 2019-07-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0002_auto_20190717_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedquotes',
            name='QtyLookup',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
