# Generated by Django 2.1 on 2019-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='Contact',
            field=models.CharField(default='untitled', max_length=25),
            preserve_default=False,
        ),
    ]
