# Generated by Django 2.1 on 2019-07-15 16:08

from django.db import migrations
from Quotes.models import merge_models

class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0004_quote_contact'),
    ]

    operations = [
        migrations.RunPython(merge_models),
    ]
