# Generated by Django 2.1 on 2019-07-17 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0006_auto_20190715_1806'),
    ]

    operations = [
        migrations.RunPython(merge_models),
    ]
