# Generated by Django 2.1 on 2019-07-17 13:04

from django.db import migrations
from Quotes.models import merge_models

class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0005_auto_20190715_1608'),
    ]

    operations = [
        migrations.RunPython(merge_models),
    ]
